site_name: Gens Julia
site_url: !ENV [SITE_URL, 'https://sosiristseng.github.io/gensjulia/']
site_author: Wen-Wei Tseng

# Repository
repo_url: !ENV [REPO_URL, 'https://github.com/sosiristseng/gensjulia/']
repo_name: !ENV [REPO_NAME, 'sosiristseng/gensjulia']
edit_uri: 'edit/main/docs/' # Leave blank to disable the edit button,

copyright: Copyright &copy; 2016 - 2023 Wen-Wei Tseng

# Nav bar
# Uncomment to customize nav bar
# nav:
#   - Home: index.md
#   - About: about.md
#   - Blog:
#     - blog/index.md
#   - Markdown syntax:
#       - Basic markdown syntax: markdown/basic.md
#       - Advanced markdown syntax: markdown/advanced.md
#   - Tags: tags.md

# MkDocs plugins
plugins:
  - search
  - ezlinks
  - callouts
  - git-revision-date-localized:
      enabled: !ENV [CI, false]
      enable_creation_date: !ENV [CI, false]

# Theme configuration
# https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  custom_dir: overrides
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    # - navigation.indexes # Not compatible with toc.integrate
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
    # - navigation.expand

  icon:
    repo: fontawesome/brands/github-alt

exclude_docs: |
  drafts/
  .obsidian/
  _templates/

# Social buttons at bottom
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sosiristseng
    - icon: fontawesome/brands/github
      link: https://github.com/sosiristseng
    - icon: fontawesome/brands/orcid
      link: https://orcid.org/0000-0003-3858-4622

# Extensions:
# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown/
# https://python-markdown.github.io/extensions/
# https://facelessuser.github.io/pymdown-extensions/
markdown_extensions:
  - nl2br  # for mkdocs-callouts
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
      toc_depth: 4
  # - pymdownx.arithmatex:
  #     generic: true
  # - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem:
      smart_enable: all
  # - pymdownx.critic
  - pymdownx.details
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:material.extensions.emoji.twemoji
  #     emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shortener: true
      user: 'sosiristseng'
      repo: 'template-mkdocs-material'
  # - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

# extra_javascript:
#   - _javascripts/config.js
#   - https://polyfill.io/v3/polyfill.min.js?features=es6
#   - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - _stylesheets/extra.css
